USE master
GO
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'tempdev', SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp2',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp3',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp4',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp5',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp6',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp7',   SIZE = 10GB , FILEGROWTH = 1GB );
ALTER DATABASE tempdb MODIFY FILE ( NAME = N'temp8',   SIZE = 10GB , FILEGROWTH = 1GB );
GO